nameOverride: service-c
image:
  repository: nginxinc/nginx-unprivileged
  tag: "1.25-alpine"
containerPort: 8080
service:
  port: 80
securityContext:
  runAsNonRoot: true
  runAsUser: 101
livenessProbe:
  httpGet: { path: /, port: http }
readinessProbe:
  httpGet: { path: /, port: http }
resources:
  requests: { cpu: "100m", memory: "128Mi" }
  limits:   { cpu: "500m", memory: "256Mi" }
hpa:
  enabled: false
