nameOverride: ""
fullnameOverride: ""

replicaCount: 2

image:
  repository: nginx
  tag: "1.25"
  pullPolicy: IfNotPresent

containerPort: 80

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"

# health checks (required by schema)
livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

# security defaults (tighten as needed)
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000

containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["ALL"]

# HPA (can be disabled per service)
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

# PDB (1 replica can be unavailable during node ops)
pdb:
  enabled: true
  maxUnavailable: 1

env: []
envFrom: []
nodeSelector: {}
tolerations: []
affinity: {}
args: []
