apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: env-dev
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/tonyrizzotto/argocd-charts.git
        revision: main
        directories:
          - path: apps/dev/*     # <- each subfolder = one app
  template:
    metadata:
      name: '{{path.basename}}-dev'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/tonyrizzotto/argocd-charts.git
        targetRevision: main
        path: apps/dev/{{path.basename}}   # <- point to that subfolder
        directory:
          recurse: true
      destination:
        server: https://kubernetes.default.svc
        namespace: dev
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
