apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: env-dev
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/tonyrizzotto/argocd-charts.git
        revision: main
        directories:
          - path: apps/dev/*             # each folder is a service
  template:
    metadata:
      name: '{{path.basename}}-dev'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/tonyrizzotto/argocd-charts.git
        targetRevision: main
        path: charts/service             # shared chart
        helm:
          valueFiles:
            - apps/dev/{{path.basename}}/values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: dev
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
