apiVersion: v1
kind: Service
metadata:
  name: {{ include "service.fullname" . }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "service.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
